<?php




/**
 * Implements hook_install().
 */
function bakery_install() {

  // Set default themes
  $enable = array(
    'theme_default' => 'bootstrap',
    'admin_theme' => 'adminimal',
  );
  theme_enable($enable);
  foreach ($enable as $var => $theme) {
    if (!is_numeric($var)) {
      variable_set($var, $theme);
    }
  }

  // Disable the default Bartik theme/s
  theme_disable(array('bartik', 'responsive_bartik'));
}


